@echo off
echo ========================================
echo    IntelliJ Performance Optimizer
echo ========================================
echo.

REM Tìm IntelliJ version và username
for /f "tokens=*" %%i in ('dir "C:\Users\%USERNAME%\AppData\Roaming\JetBrains" /b /ad 2^>nul') do (
    if "%%i" neq "" (
        set INTELLIJ_VERSION=%%i
        goto :found
    )
)

:found
if "%INTELLIJ_VERSION%"=="" (
    echo Khong tim thay IntelliJ IDEA trong AppData\Roaming\JetBrains
    echo Hay cai dat IntelliJ IDEA truoc khi chay script nay
    pause
    exit /b 1
)

echo Tim thay IntelliJ version: %INTELLIJ_VERSION%
echo.

REM Tạo đường dẫn đến file vmoptions
set VMOPTIONS_FILE=C:\Users\%USERNAME%\AppData\Roaming\JetBrains\%INTELLIJ_VERSION%\idea64.exe.vmoptions

echo Dang toi uu IntelliJ performance...
echo File cau hinh: %VMOPTIONS_FILE%
echo.

REM Tạo backup
if exist "%VMOPTIONS_FILE%" (
    copy "%VMOPTIONS_FILE%" "%VMOPTIONS_FILE%.backup"
    echo Da tao backup: %VMOPTIONS_FILE%.backup
)

REM Tạo file cấu hình tối ưu
echo # IntelliJ IDEA Performance Configuration > "%VMOPTIONS_FILE%"
echo # Generated by Performance Optimizer >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Memory Settings - Tang memory cho IntelliJ >> "%VMOPTIONS_FILE%"
echo -Xms2048m >> "%VMOPTIONS_FILE%"
echo -Xmx4096m >> "%VMOPTIONS_FILE%"
echo -XX:ReservedCodeCacheSize=512m >> "%VMOPTIONS_FILE%"
echo -XX:+UseG1GC >> "%VMOPTIONS_FILE%"
echo -XX:SoftRefLRUPolicyMSPerMB=50 >> "%VMOPTIONS_FILE%"
echo -XX:CICompilerCount=2 >> "%VMOPTIONS_FILE%"
echo -XX:+HeapDumpOnOutOfMemoryError >> "%VMOPTIONS_FILE%"
echo -XX:-OmitStackTraceInFastThrow >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Performance Optimizations >> "%VMOPTIONS_FILE%"
echo -XX:+UseStringDeduplication >> "%VMOPTIONS_FILE%"
echo -XX:+OptimizeStringConcat >> "%VMOPTIONS_FILE%"
echo -XX:+UseCompressedOops >> "%VMOPTIONS_FILE%"
echo -XX:+UseCompressedClassPointers >> "%VMOPTIONS_FILE%"
echo -XX:+UnlockExperimentalVMOptions >> "%VMOPTIONS_FILE%"
echo -XX:+UseZGC >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Garbage Collection >> "%VMOPTIONS_FILE%"
echo -XX:MaxGCPauseMillis=200 >> "%VMOPTIONS_FILE%"
echo -XX:G1HeapRegionSize=16m >> "%VMOPTIONS_FILE%"
echo -XX:G1NewSizePercent=30 >> "%VMOPTIONS_FILE%"
echo -XX:G1MaxNewSizePercent=40 >> "%VMOPTIONS_FILE%"
echo -XX:G1MixedGCCountTarget=8 >> "%VMOPTIONS_FILE%"
echo -XX:G1MixedGCLiveThresholdPercent=85 >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Code Cache >> "%VMOPTIONS_FILE%"
echo -XX:InitialCodeCacheSize=240m >> "%VMOPTIONS_FILE%"
echo -XX:ReservedCodeCacheSize=512m >> "%VMOPTIONS_FILE%"
echo -XX:+UseCodeCacheFlushing >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Threading >> "%VMOPTIONS_FILE%"
echo -XX:ThreadPriorityPolicy=1 >> "%VMOPTIONS_FILE%"
echo -XX:ThreadStackSize=2048 >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # File System >> "%VMOPTIONS_FILE%"
echo -Dfile.encoding=UTF-8 >> "%VMOPTIONS_FILE%"
echo -Dsun.jnu.encoding=UTF-8 >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # IntelliJ Specific >> "%VMOPTIONS_FILE%"
echo -Didea.system.path=C:\Users\%USERNAME%\.%INTELLIJ_VERSION%\system >> "%VMOPTIONS_FILE%"
echo -Didea.config.path=C:\Users\%USERNAME%\.%INTELLIJ_VERSION%\config >> "%VMOPTIONS_FILE%"
echo -Didea.plugins.path=C:\Users\%USERNAME%\.%INTELLIJ_VERSION%\config\plugins >> "%VMOPTIONS_FILE%"
echo -Didea.log.path=C:\Users\%USERNAME%\.%INTELLIJ_VERSION%\system\log >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Disable unnecessary features for better performance >> "%VMOPTIONS_FILE%"
echo -Didea.cycle.buffer.size=1024 >> "%VMOPTIONS_FILE%"
echo -Didea.max.intellisense.filesize=2500 >> "%VMOPTIONS_FILE%"
echo -Didea.auto.reload.changed.files=true >> "%VMOPTIONS_FILE%"
echo -Didea.auto.save.if.inactive=true >> "%VMOPTIONS_FILE%"
echo -Didea.auto.save.if.inactive.seconds=30 >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Enable parallel compilation >> "%VMOPTIONS_FILE%"
echo -Dcompiler.parallel=true >> "%VMOPTIONS_FILE%"
echo -Dcompiler.parallel.threads=4 >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # Disable some heavy features >> "%VMOPTIONS_FILE%"
echo -Didea.background.tasks.enabled=false >> "%VMOPTIONS_FILE%"
echo -Didea.usage.statistics.enabled=false >> "%VMOPTIONS_FILE%"
echo. >> "%VMOPTIONS_FILE%"
echo # JavaFX specific optimizations >> "%VMOPTIONS_FILE%"
echo -Dprism.order=hw >> "%VMOPTIONS_FILE%"
echo -Dprism.vsync=false >> "%VMOPTIONS_FILE%"
echo -Djavafx.css.validation=false >> "%VMOPTIONS_FILE%"
echo -Djavafx.animation.fullspeed=true >> "%VMOPTIONS_FILE%"

echo.
echo ========================================
echo    Toi uu hoan tat!
echo ========================================
echo.
echo Cac thay doi da duoc ap dung:
echo - Tang memory: 2GB -> 4GB
echo - G1GC garbage collector
echo - Parallel compilation
echo - Optimized code cache
echo - Disabled heavy features
echo.
echo Hay restart IntelliJ IDEA de ap dung cac thay doi!
echo.
echo Backup file: %VMOPTIONS_FILE%.backup
echo.
pause 